"""add documents and historique tables

Revision ID: 2c31a64765ae
Revises: 7cff5263a9c1
Create Date: 2026-04-13 21:41:02.450812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c31a64765ae'
down_revision: Union[str, Sequence[str], None] = '7cff5263a9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom_fichier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chemin', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('type_fichier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('taille', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploade_par', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('documents_dossier_id_fkey')),
    sa.ForeignKeyConstraint(['uploade_par'], ['utilisateurs.id'], name=op.f('documents_uploade_par_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_table('historiques',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('historiques_dossier_id_fkey')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('historiques_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historiques_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historiques')
    op.drop_table('documents')
    # ### end Alembic commands ###