"""add type_beneficiaire secteur localisation

Revision ID: 363476b996ce
Revises: 09f880f5851e
Create Date: 2026-04-16 14:36:07.653688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '363476b996ce'
down_revision: Union[str, Sequence[str], None] = '09f880f5851e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('type_beneficiaire', sa.String(length=50), nullable=True))
    op.add_column('utilisateurs', sa.Column('secteur_activite', sa.String(length=100), nullable=True))
    op.add_column('utilisateurs', sa.Column('localisation', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'localisation')
    op.drop_column('utilisateurs', 'secteur_activite')
    op.drop_column('utilisateurs', 'type_beneficiaire')
    op.create_table('historiques',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('historiques_dossier_id_fkey')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('historiques_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historiques_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom_fichier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chemin', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('type_fichier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('taille', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploade_par', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cree_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('documents_dossier_id_fkey')),
    sa.ForeignKeyConstraint(['uploade_par'], ['utilisateurs.id'], name=op.f('documents_uploade_par_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
